name: API Tests

on:
  push:
    branches:
      - main
      - preprod
      - prod
      
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17 
        env:
          POSTGRES_USER: oikia
          POSTGRES_PASSWORD: oikia
          POSTGRES_DB: oikia
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U oikia" --health-timeout=5s --health-start-period=10s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          make install
      
      
      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -U oikia -d oikia; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/test_db" >> $GITHUB_ENV

      - name: Run tests
        run: make test
